services:
  web:
    image: node:22
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS
    command: sh -c "npm install && npx nodemon --legacy-watch index.js"
    restart: unless-stopped

volumes:
  node_modules:
